name: Deploy package to PyPI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update version in pyproject.toml from current git tag
        run: >-
          sed -i "s/0\\.0\\.0\\.dev0/${GITHUB_REF/refs\/tags\/v/}/g" pyproject.toml

      - name: Update version in setup.py from current git tag
        run: >-
          sed -i "s/0\\.0\\.0\\.dev0/${GITHUB_REF/refs\/tags\/v/}/g" setup.py

      - run: >-
          docker run --rm -v ${{ github.workspace }}:/app quay.io/pypa/manylinux2014_x86_64:2024-09-16-ab73a4b bash -c '
            cd /app &&
            /opt/python/cp311-cp311/bin/python -m build &&
            auditwheel repair $(ls dist/*.whl) &&
            rm dist/*.whl &&
            cp wheelhouse/*.whl dist
          '

      - uses: actions/upload-artifact@v4
        with:
          path: ./dist

  deploy:
    needs: [build]
    environment:
      name: pypi
      url: https://pypi.org/project/stream-inflate/

    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages_dir: artifact/
