name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        include:
          - python-version: "3.6.7"
            os: "ubuntu-20.04"
          - python-version: "3.7.1"
            os: "ubuntu-20.04"
          - python-version: "3.8.0"
            os: "ubuntu-20.04"
          - python-version: "3.9.0"
            os: "ubuntu-20.04"
          - python-version: "3.10.0"
            os: "ubuntu-20.04"
          - python-version: "3.11.0"
            os: "ubuntu-20.04"
          - python-version: "3.12.0"
            os: "ubuntu-20.04"
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: '${{ matrix.python-version }}'
      - name: "Enable code coverage"
        run: |
          echo '# cython: linetrace=True' | cat - stream_inflate.py > temp && mv temp stream_inflate.py
          echo '# distutils: define_macros=CYTHON_TRACE=1' | cat - stream_inflate.py > temp && mv temp stream_inflate.py
      - name: "Install python dependencies"
        run: |
          pip install '.[dev]'
          python setup.py build_ext --inplace
      - name: "Run tests"
        run: |
          pytest --cov -v
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
